---

  - apt: name=wget state=latest
    when: (ansible_os_family == "Debian")

  - yum: name=wget state=latest
    when: (ansible_os_family == "RedHat")

  - lineinfile: "dest=/etc/wgetrc regexp='^#https_proxy = ' line='https_proxy = {{proxy_url}}' state=present"
  - lineinfile: "dest=/etc/wgetrc regexp='^#http_proxy = ' line='http_proxy = {{proxy_url}}' state=present"
  - lineinfile: "dest=/etc/wgetrc regexp='^#ftp_proxy = ' line='ftp_proxy = {{proxy_url}}' state=present"
  - lineinfile: "dest=/etc/wgetrc regexp='^#use_proxy = ' line='use_proxy = on' state=present"
  - lineinfile: "dest=/etc/wgetrc line='no_proxy = {{no_proxy}}' state=present"
