---

  - name: ensure fitnesse container is running
    docker:
#begin registry auth
      insecure_registry: yes
      use_tls: "no"
      registry: "{{docker_registry.host}}/"
      username: "{{docker_registry.username}}"
      password: "{{docker_registry.password}}"
      email: "{{docker_registry.email}}"
#end registry auth
      image: "{{docker_registry.host}}/fitnesse:latest"
      memory_limit: 1024MB
      name: "fitnesse"
      pull: missing
      ports:
        - "{{interface}}:{{fitnesse_port}}:80"
      volumes:
        - "/opt/fitnesse/FitNesseRoot:/opt/fitnesse/FitNesseRoot:rw"
      state: reloaded
      pull: missing
      restart_policy: always
    register: start_fitnesse
