---

  - file: path=/tmp/fitnesse state=directory

  - name: stat fitnesse-standalone jar
    local_action: stat path="fitnesse-standalone.jar"
    sudo: no
    register: fitnesse_standalone

  - fail: msg="fitnesse-standalone.jar is missing. Please download it 'curl --insecure -O {{fitnesse_url}}'"
    when: not fitnesse_standalone.stat.exists

  - copy: src={{item}} dest=/tmp/fitnesse/
    with_items:
      - .dockerignore
      - fitnesse-standalone.jar

  - template: src=Dockerfile dest=/tmp/fitnesse/

  - name: build fitnesse
    docker_image:
      path: "/tmp/fitnesse"
      name: "fitnesse"
      state: present
      tag: "latest"
    register: build_fitnesse

