---

  - name: Install Nginx
    apt:
      name: nginx
      state: installed
    when: ansible_os_family == "Debian"

  - name: Install Nginx
    yum:
      name: nginx
      state: installed
    when: ansible_os_family == "Redhat"

  - name: ensure nginx daemon is running
    service: name=nginx state=running

  - include: vhost.yml

