---

  - name: Create a VirtualHost file
    template:
      src=vhosts.conf
      dest=/etc/nginx/sites-available/{{ vhost }}
      owner=root
      group=root
      mode=0644
    notify:
      - restart nginx

  - file: src=/etc/nginx/sites-available/{{ vhost }} dest=/etc/nginx/sites-enabled/{{ vhost }} owner=root group=root state=link
    notify:
      - restart nginx

