---

  - file: path=/jenkins/docker state=directory

  - name: copy jenkins docker files
    copy: src={{item}} dest=/jenkins/docker/
    with_items:
        - tomcat
    register: jenkins_docker_files

  - name: copy Dockerfile
    template: src=Dockerfile.j2 dest=/jenkins/docker/Dockerfile
    register: jenkins_docker_file

  - name: copy jenkins run script
    template: src=run.sh.j2 dest=/jenkins/docker/run.sh
    register: jenkins_run

  - name: ensure jenkins present
    docker_image: path="/jenkins/docker"
                  name="busybox-jenkins-{{jenkins_version}}"
                  tag=latest
                  state=present
    register: ensure_jenkins
